testing_params:
  test: true
  test_freq: 10000  #10000
  num_steps: 600

learning_params:
  total_units: 500
  step_unit: 10000  # 10000
  lr: 0.00005  # data_augment: false:1e-5, true:5e-5
  epsilon: 0.1
  gamma: 0.9
  buffer_size: 50000
  train_freq: 1
  batch_size: 32
  target_network_update_freq: 100  # 100
  learning_starts: 1000
  tabular_case: false
  use_random_maps: false
  use_double_dqn: false
  prioritized_replay: false
  data_augment: true  # for type=="embedding" only

model_params:
  tabular_case: false
  num_hidden_layers: 6
  num_neurons: 256  # 256

  type: "embedding" # "transformer" or "embedding"
  enc_feature: "concat" # "concat" or "fine-tune"

  # transformer params
  max_ltl_len: 25
  d_model: 64
  nhead: 8
  num_encoder_layers: 4
  d_out: 16 # output_dim of the encoding module
  pool: 'mean'
  dim_feedforward: 256
  dropout: 0.0
  layer_norm_eps: 0.00001
  TFixup: true

  # embedding params
  max_num_formulas: 40  # max num of LTL formulas
  embedding_dim: 32 # 32
