testing_params:
  test: true
  test_freq: 1000
  num_steps: 1000

learning_params:
  tabular_case: false
  total_units: 1000
  step_unit: 1000
  lr: 0.00001
  gamma: 0.9
  buffer_size: 2048
  train_freq: 1
  batch_size: 32  # mini-batch, 32 or 64
  learning_starts: 1
  adam_eps: 0.00001

  use_random_maps: false
  use_grad_clip: true
  use_lr_decay: true

  # ppo params
  clip_rate: 0.2
  lam: 0.95
  n_updates: 10
  policy_loss_coef: 1.0
  value_loss_coef: 1.0
  entropy_loss_coef: 0


model_params:
  action_bound: 1.0
  tabular_case: false
  num_hidden_layers: 3
  num_neurons: 64

