testing_params:
  test: true
  test_freq: 500
  num_steps: 1000

learning_params:
  total_units: 300  # 100*3
  step_unit: 500
  gamma: 0.9
  tabular_case: true
  epsilon: 0.1
  lr: 1.0  # 1.0 best in deterministic cases
  batch_size: 1
  learning_starts: 1
  buffer_size: 1
  target_network_update_freq: 1
  train_freq: 1
  transfer_methods: "equivalent"  # "none"/"equivalent"/"value_com"
  # only available for transfer_methods=="value_com"
  transfer_normalization: true
  value_com: # compose methods for operators "and", "or", "then" respectively
    - "average"
    - "max"
    - "left"

  # only available for distill_att=="n_emb"
  ltl_correlation_weight: 100 # weight>=0, the bias before softmax of correlated policies (Q-values)
  att_lr: 0.1
  eval_by_student: true
  # [initial, end], adaptive decrease
  decrease_speed: 10
  distill_coefs:
    - 0
    - 0
  teacher_rates:
    - 1
    - 0

model_params:
  tabular_case: true
  # network structure of attention for distillation
  distill_att: "n_emb" # "none"/"n_emb"