testing_params:
  test: true
  test_freq: 500
  num_steps: 1000

learning_params:
  total_units: 500
  step_unit: 500
  gamma: 0.9
  tabular_case: true
  epsilon: 0.1
  lr: 1.0  # 1.0?
  batch_size: 1
  learning_starts: 1
  buffer_size: 1
  target_network_update_freq: 1
  train_freq: 1
  stochastic_data_augment: true # false: as qrm does; true: weighted sum over probabilistic next rm states
  use_label_prob: true

model_params:
  tabular_case: true
