testing_params:
  test: true
  test_freq: 1000
  num_steps: 1000

learning_params:
  total_units: 1200  # 400*4
  step_unit: 1000
  gamma: 0.9
  tabular_case: true
  epsilon: 0.1
  lr: 1.0  # 1.0 best in deterministic cases
  batch_size: 1
  learning_starts: 1
  buffer_size: 1
  target_network_update_freq: 1
  train_freq: 1
  transfer_methods: "equivalent"  # "none"/"equivalent"/"value_com"/"distill"
  # only available for transfer_methods=="value_com"
  transfer_normalization: true
  value_com: # compose methods for operators "and", "or", "then" respectively
    - "average"
    - "max"
    - "left"

  # only available for distill_att=="n_emb"
  ltl_correlation_weight: 100 # 0<=weight<1, the sum weights of correlated policies (Q-values)
  att_lr: 0.1
  w_q_loss_rate: 1.0
  diff_loss_rate: 0
  distill_rate: 1
  adaptive_distill: true

model_params:
  tabular_case: true
  # network structure of attention for distillation
  distill_att: "n_emb" # "none"/"n_emb"
