testing_params:
  test: true
  test_freq: 1000
  num_steps: 1000

learning_params:
  total_units: 1600  # 400*4
  step_unit: 1000
  gamma: 0.9
  tabular_case: true
  epsilon: 0.1
  lr: 1.0  # 1.0 best in deterministic cases
  batch_size: 1
  learning_starts: 1
  buffer_size: 1
  target_network_update_freq: 1
  train_freq: 1
  transfer_methods: "value_com"  # "none"/"equivalent"/"value_com"/"distill"
  # only available for transfer_methods=="value_com"
  transfer_normalization: true
  value_com: # compose methods for operators "and", "or", "then" respectively
    - "average"
    - "max"
    - "left"

model_params:
  tabular_case: true
